lcd_fillRect(UPPERRECTANGLE_X0+x, UPPERRECTANGLE_Y0+y, UPPERRECTANGLE_X1+x, UPPERRECTANGLE_Y1+y, CAR_CLR);
lcd_fillRect(BASERECTANGLE_X0+x, BASERECTANGLE_Y0+y, BASERECTANGLE_X1+x, BASERECTANGLE_Y1+y, CAR_CLR);
lcd_fillTriangle(HOOD_X0+x, HOOD_Y0+y, HOOD_X1+x, HOOD_Y1+y, HOOD_X2+x, HOOD_Y2+y, CAR_CLR);
lcd_fillRoundRect(WINDOW_X0+x, WINDOW_Y0+y, WINDOW_X1+x, WINDOW_Y1+x, WINDOW_RADIUS, WINDOW_CLR);
lcd_fillRoundRect(WINDOW_X0+WINDOW_DISTANCE_X_OFFSET+x, WINDOW_Y0+y, WINDOW_X1+WINDOW_DISTANCE_X_OFFSET+x, WINDOW_Y1+y, WINDOW_RADIUS, WINDOW_CLR);
lcd_fillCircle(BASE_WHEEL_X0+x, BASE_WHEEL_Y0+y, BIG_WHEEL_RAD+x, TIRE_CLR);
lcd_fillCircle(BASE_WHEEL_X0+WHEEL_DISTANCE_X_OFFSET+x, BASE_WHEEL_Y0+y, BIG_WHEEL_RAD, TIRE_CLR);
lcd_fillCircle(BASE_WHEEL_X0+x, BASE_WHEEL_Y0+y, SMALL_WHEEL_RAD, HUB_CLR);
lcd_fillCircle(BASE_WHEEL_X0+WHEEL_DISTANCE_X_OFFSET+x, BASE_WHEEL_Y0+y, SMALL_WHEEL_RAD, HUB_CLR);