
#include <stdint.h>

#define CAR-HORN-BEEP-BEEP-TWO-BEEPS-HONK-HONK-6188_BITS_PER_SAMPLE 8
#define CAR-HORN-BEEP-BEEP-TWO-BEEPS-HONK-HONK-6188_SAMPLE_RATE 24000
#define CAR-HORN-BEEP-BEEP-TWO-BEEPS-HONK-HONK-6188_SAMPLES 17267

extern const uint8_t car-horn-beep-beep-two-beeps-honk-honk-6188[CAR-HORN-BEEP-BEEP-TWO-BEEPS-HONK-HONK-6188_SAMPLES];
